version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/World-of-Alcohol # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8u171-jdk # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run: mvn dependency:go-offline # gets the project dependencies
      - run: mvn test

    deploy:
      docker:
      - image: circleci/buildpack-deps:trusty
      steps:
      - checkout
      - run:
          name: Deploy app on heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
          - build